create table leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  niche text,
  location text,
  company_name text,
  website_url text not null unique,
  rating numeric,
  review_count integer,
  problem_identified text,
  ai_solution_idea text,
  email_draft text,
  engine_used text,
  status text default 'discovered'
);
